
CREATE TABLE DEPARTMENTS(
	DEPT_NO VARCHAR(50) NOT NULL,
	DEPT_NAME VARCHAR(50) NOT NULL
);

SELECT * FROM DEPARTMENTS

CREATE TABLE DEPARTMENT_EMP(
	EMP_NO VARCHAR(50) NOT NULL,
	DEPT_NO VARCHAR(50) NOT NULL
);
select * from department_emp

CREATE TABLE DEPT_MGR(
	DEPT_NO VARCHAR(50) NOT NULL,
	EMP_NO VARCHAR(50) NOT NULL
);
select * from dept_mgr
CREATE TABLE EMPLOYEES(
	EMP_NO VARCHAR(50) NOT NULL,
	EMP_TITLE VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	SEX VARCHAR(50) NOT NULL,
	HIRE_DATE DATE NOT NULL
);
select * from employees

CREATE TABLE SALARIES(
	EMP_NO VARCHAR(50) NOT NULL,
	SALARY INT NOT NULL
);
SELECT * FROM SALARIES

CREATE TABLE TITLES(
	TITLE_ID VARCHAR(50) NOT NULL,
 	TITLE VARCHAR(50) NOT NULL
);

SELECT * FROM TITLES
--LISTING OUT EMP_NO, LAST NAME, FIRST NAME, SEX, SALARY FROM EMPLOYEES TABLE.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME,EMPLOYEES.SEX,SALARIES.SALARY
FROM EMPLOYEES
JOIN SALARIES
ON EMPLOYEES.EMP_NO = SALARIES.EMP_NO
--LISTING OUT FIRST NAME, LAST NAME , AND HIRE DATE FOR SOMEONE HIRED IN 1986
SELECT 
FIRST_NAME,
LAST_NAME,
HIRE_DATE
FROM EMPLOYEES WHERE HIRE_DATE >='1986-01-01' and hire_date <='1986-12-31'

--List the manager of each department along with their department number, department name, 
--employee number, last name, and first name.

SELECT 
DM.dept_no,
DEPARTMENTS.DEPT_NAME,
EMP.EMP_NO,
EMP.FIRST_NAME,
EMP.LAST_NAME
FROM DEPT_MGR AS DM
JOIN EMPLOYEES AS EMP 
ON DM.EMP_NO = EMP.EMP_NO
LEFT JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO=DM.DEPT_NO


--List the department number for each employee along with that employee’s employee number, 
--last name, first name, and department name.

SELECT DEPARTMENT_EMP.DEPT_NO,DEPARTMENTS.DEPT_NAME, DEPARTMENT_EMP.EMP_NO,EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME
FROM DEPARTMENT_EMP
JOIN EMPLOYEES
ON DEPARTMENT_EMP.EMP_NO=EMPLOYEES.EMP_NO
LEFT JOIN DEPARTMENTS
ON DEPARTMENT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO

-- List first name, last name, and sex of each employee whose first name is Hercules and whose last name begins with the letter B.
SELECT FIRST_NAME, LAST_NAME, SEX FROM EMPLOYEES 
WHERE LAST_NAME LIKE 'B%' OR FIRST_NAME LIKE 'HERCULES'

-- List each employee in the Sales department, including their employee number, last name, and first name.
SELECT DEPARTMENT_EMP.DEPT_NO, EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME FROM DEPARTMENT_EMP
JOIN EMPLOYEES
ON DEPARTMENT_EMP.EMP_NO=EMPLOYEES.EMP_NO
WHERE DEPARTMENT_EMP.DEPT_NO LIKE 'd007'

-- List each employee in the Sales and Development departments, including their employee number, 
-- last name, first name, and department name.

SELECT DEPARTMENT_EMP.DEPT_NO, EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPT_NAME FROM EMPLOYEES
JOIN DEPARTMENT_EMP
ON EMPLOYEES.EMP_NO=DEPARTMENT_EMP.EMP_NO
LEFT JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO=DEPARTMENT_EMP.DEPT_NO
WHERE DEPARTMENT_EMP.DEPT_NO LIKE 'd007' or DEPARTMENT_EMP.DEPT_NO like 'd005'

SELECT * FROM DEPARTMENTS

-- List the frequency counts, in descending order, of all the employee last names (that is, how many employees share each last name).
SELECT LAST_NAME, COUNT(DISTINCT LAST_NAME) AS FREQUENCY
FROM EMPLOYEES
GROUP BY LAST_NAME
ORDER BY FREQUENCY DESC






